# Adapted from
# https://docs.haskellstack.org/en/stable/travis_ci/

sudo: required
dist: trusty

language: minimal

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

matrix:
  include:
  # The Stack builds. We can pass in arbitrary Stack arguments via the ARGS
  # variable, such as using --stack-yaml to point to a different file.
  - env: BUILD=stack ARGS=""
    compiler: ": #stack default"

  - env: BUILD=stack ARGS="--resolver lts-9 --stack-yaml stack-travis.yaml"
    compiler: ": #stack LTS 9"

  - env: BUILD=stack ARGS="--resolver lts-10 --stack-yaml stack-travis.yaml"
    compiler: ": #stack LTS 10"

  - env: BUILD=stack ARGS="--resolver lts-11"
    compiler: ": #stack LTS 11"

  - env: BUILD=stack ARGS="--resolver lts-12"
    compiler: ": #stack LTS 12"

  - env: BUILD=npm
    compiler: ": #npm"

  - env: BUILD=integration RESOLVER_SERIES=lts-9
    compiler: ": #integration LTS 9"

  - env: BUILD=integration RESOLVER_SERIES=lts-10
    compiler: ": #integration LTS 10"

  - env: BUILD=integration RESOLVER_SERIES=lts-11
    compiler: ": #integration LTS 11"

  - env: BUILD=integration RESOLVER_SERIES=lts-12
    compiler: ": #integration LTS 12"

before_install: source ./travis/before_install

install: source ./travis/install

script: source ./travis/build

deploy:
  provider: script
  script: ./travis/deploy
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition:
      - '$BUILD = stack'
      - '$ARGS = ""'
      - '$(uname) = Linux'
      - '$TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$'
